In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Everything works!")

Matplotlib is building the font cache; this may take a moment.

Everything works!

In [4]:
df = pd.read_csv("../data/raw/digikala-comments.csv")

df.head()

,id,title,body,created_at,rate,recommendation_status,is_buyer,product_id,advantages,disadvantages,likes,dislikes,seller_title,seller_code,true_to_size_rate
0,53672599,پیشنهاد نمیشود,به درد نمیخوره,23 شهریور 1402,1.0,not_recommended,True,252058,NaN,NaN,0,0,دیجی‌کالا,5A52N,NaN
1,9897229,بسته بندی بد,می‌تونست به عنوان یه کالای فرهنگی بهتر بسته بن...,16 تیر 1399,0.0,recommended,True,252058,['تجربه جالبی بود برام '],['بسته بندی جالبی نداشت'],1,0,دیجی‌کالا,5A52N,NaN
2,38074516,برس ریمل,بسته بندیش خوب بود\r\n کاربرد و کیفیتشم خیلی خ...,26 مرداد 1401,0.0,recommended,True,3331597,NaN,NaN,0,0,آرالیا بیوتی,ADM47,NaN
3,18628562,خوبه و خوشرنگ,به نظرم خوبه فقط یکم ظریفه. از رنگش خوشم اومد ...,28 اسفند 1399,0.0,recommended,True,3331329,NaN,NaN,0,0,اینجاست آ,9ZMCZ,NaN
4,53301258,برس رنگ مو,معمولیه اگه واسه خونه رنگ کردن شخصی میخواین او...,12 شهریور 1402,3.0,recommended,True,3255700,NaN,NaN,0,0,گالری آرایشی به سیما,CDWHA,NaN

In [5]:
df.shape

(6156289, 15)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6156289 entries, 0 to 6156288
Data columns (total 15 columns):
 #   Column                 Dtype
---  ------                 -----
 0   id                     int64
 1   title                  object
 2   body                   object
 3   created_at             object
 4   rate                   float64
 5   recommendation_status  object
 6   is_buyer               bool
 7   product_id             int64
 8   advantages             object
 9   disadvantages          object
 10  likes                  int64
 11  dislikes               int64
 12  seller_title           object
 13  seller_code            object
 14  true_to_size_rate      object
dtypes: bool(1), float64(1), int64(4), object(9)
memory usage: 663.4+ MB

In [8]:
df.describe()

                 id          rate    product_id         likes      dislikes
count  6.156289e+06  6.156289e+06  6.156289e+06  6.156289e+06  6.156289e+06
mean   3.704709e+07  3.648286e+00  3.908983e+06  4.503171e-01  8.687068e-02
std    1.393243e+07  1.861854e+00  3.015881e+06  2.294114e+00  8.313516e-01
min    9.815860e+05  0.000000e+00  7.602000e+03  0.000000e+00  0.000000e+00
25%    2.731234e+07  3.000000e+00  1.532375e+06  0.000000e+00  0.000000e+00
50%    4.044773e+07  4.000000e+00  3.183184e+06  0.000000e+00  0.000000e+00
75%    4.897122e+07  5.000000e+00  5.992988e+06  0.000000e+00  0.000000e+00
max    5.474516e+07  2.500000e+03  1.270221e+07  1.136000e+03  3.360000e+02

In [9]:
df.isnull().sum()

id                             0
title                    2865062
body                         637
created_at                     0
rate                           0
recommendation_status     894426
is_buyer                       0
product_id                     0
advantages               5448084
disadvantages            5744017
likes                          0
dislikes                       0
seller_title              302181
seller_code               302181
true_to_size_rate        6065516
dtype: int64

In [10]:
df.columns

Index(['id', 'title', 'body', 'created_at', 'rate', 'recommendation_status',
       'is_buyer', 'product_id', 'advantages', 'disadvantages', 'likes',
       'dislikes', 'seller_title', 'seller_code', 'true_to_size_rate'],
      dtype='object')